### ISSUE TITLE
sign transaction failed

### ISSUE THREAD

**Issue by firmianavan** [ontio/ontology-ts-sdk#130]
Hello, here is my demo running on node11.3, it throws when signing the transaction :
```
const Account = require('ontology-ts-sdk').Account;
const Crypto = require('ontology-ts-sdk').Crypto;
const ontTxBuilder = require('ontology-ts-sdk').OntAssetTxBuilder;

//account generate by ontology-cli
let keystore = `{
    "address":"AJaz5KyntxxjExiRNYayXy9Xbfejp6V2AS",
    "enc-alg":"aes-256-gcm",
    "key":"PeR8p8qFaFUuUyiUjvD3Blk3EUXpY44D2lo5pWJtSIUpbEnrN43KhnZXXsUaXLar",
    "algorithm":"ECDSA",
    "salt":"+hf+nV312ZlkhFoa65g3KA==",
    "parameters":{"curve":"P-256"},
    "label":"",
    "publicKey":"0241a879cd9328c5f45d8608aa96a8725ea0a7a851785a9255d8f901f9c6fc3ad5",
    "signatureScheme":"SHA256withECDSA",
    "isDefault":true,
    "lock":false
}`

const account = Account.parseJson(keystore);

const tokenType = "ONT";
const to = "AWxFwFUEDzRW5FZbtq81rPEuxHDNd2BWoi";

var tx = ontTxBuilder.makeTransferTx( tokenType, account.address, to, '1000000000', 300, 10000 );
const raw = account.signTransaction("123456",tx);
```
The exception 

```
Error: 53000
scrypt.ts:399
    at decryptWithGcm (file:///Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:6004:8)
    at decrypt (file:///Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:2423:88)
    at exportPrivateKey (file:///Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:269:33)
    at signTransaction (file:///Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:272:25)
    at (anonymous) (file:///Users/fanlinlin/ws/newbee-task/ont.js:31:20)
    at Module._compile (internal/modules/cjs/loader.js:719:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:9)
    at Module.load (internal/modules/cjs/loader.js:620:31)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:11)
    at Module._load (internal/modules/cjs/loader.js:552:2)
    at Module.runMain (internal/modules/cjs/loader.js:775:11)
    at startup (internal/bootstrap/node.js:300:18)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:2)
```

It is a wrapped Exception, I set a breakpoint and found the original Error in scrypt.tx:399:11 is

```
:"Unsupported state or unable to authenticate data"
stack:"Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:166:29)
    at decryptWithGcm (/Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:6002:31)
    at PrivateKey.decrypt (/Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:2423:89)
    at Account.exportPrivateKey (/Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:269:34)
    at Account.signTransaction (/Users/fanlinlin/ws/newbee-task/node_modules/ontology-ts-sdk/lib/index.js:272:26)
    at Object.<anonymous> (/Users/fanlinlin/ws/newbee-task/ont.js:31:21)\n    at Module._compile (internal/modules/cjs/loader.js:719:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)\n    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)"
```
I know little about scrypt, did I pass the wrong parameters?

**Comment by firmianavan** [comment]
```
// generate by cli `ontology account add -d`
let keystore =`{
    "address":"AYjTkGPYnjCre7D3pRECDPoTvbSU9C2fnh",
    "enc-alg":"aes-256-gcm",
    "key":"NSJk+v4i1ogqbi2/CzKoUfTnN4z5zzzR8EMtZdWWc+piNd7k5DcrCjboozcKhCM3",
    "algorithm":"ECDSA","salt":"kG7PnYjmMMAHzn/0RPPl8g==",
    "parameters":{"curve":"P-256"},"label":"",
    "publicKey":"02a96160846ad8c0eb48d87aac896095e820ec79fe64a391e50510566e064fdc11",
    "signatureScheme":"SHA256withECDSA",
    "isDefault":false,"lock":false
}`
//const priv = Crypto.PrivateKey.random(Crypto.KeyType.ECDSA, new Crypto.KeyParameters(Crypto.CurveLabel.SECP256R1));
//const account = Account.create(target,"123456","test");
//let ks2 = account.toJson();
let ks2 = `{
    "address":"ATgxxQLFZpuLQajuZQ9CHHysSMvbqYYvZg",
    "label":"test","lock":false,
    "algorithm":"ECDSA",
    "parameters":{"curve":"P-256"},
    "key":"8oH3jI8Aok5JEbiHav+ju0gagPfKhP/WZtfmeFAjq2kwHBd6ClvNpMnJS0/GLzD0",
    "enc-alg":"aes-256-gcm",
    "hash":"sha256",
    "salt":"pt2n5zmoWRNEIzy3oCNPsA==",
    "isDefault":false,
    "publicKey":"02581e507543b98c8204e824b8b8032296d16881c9c889fdafa10be08b9a09ebf9",
    "signatureScheme":"SHA256withECDSA"
}`
```

ks1 is ok, but ks2 is not.

**Comment by MickWang** [comment]
there is a optional scrypt parameter used in private key encryption and decryption.We must keep it the same.
```
ScryptParams {
    cost: number;
    blockSize: number;
    parallel: number;
    size: number;
}
```
The default value used in typescript sdk is 
```
{
    cost: 4096, // 除以2时间减半
    blockSize: 8,
    parallel: 8,
    size: 64
}
```
the value used in ontology-cli is 
{
    cost: 16384, // 除以2时间减半
    blockSize: 8,
    parallel: 8,
    size: 64
}
When you decrypt the encrypted private key or sign a transaction, you should  pass in the scrypt parameter to avoid the failing. For your problem, please add scrypt parameter used in ontology-cli as the third parameter in the `signTransaction` function.

**Comment by firmianavan** [comment]
Thank you,  it works~
