### ISSUE TITLE
Error serializing tx when using crypto curve ED25519

### ISSUE THREAD

**Issue by roccomuso** [ontio/ontology-ts-sdk#196]
Here's my example:

```javascript
const { GovernanceTxBuilder, TransactionBuilder, Crypto } = require('ontology-ts-sdk')
const { PrivateKey, Address } = Crypto

const seed = Buffer.from('05feadb3037d3afc7c878130a73b5b9e8fa6df42899dfaf874b4dfa8ab1bf4a4', 'hex')

const privateKey = new PrivateKey(seed, Crypto.KeyType.EDDSA, { curve: Crypto.CurveLabel.ED25519 })
// const privateKey = new PrivateKey(seed) // IT WORKS without EDDSA schema

//Sender's address
const address = new Address('APT4wZG9sFQfjhyfGALPXQj5UyrQ3ZCVkY')
// peers
const peerPubKeyList = ['039cadf7145731b3c868bd3528da9172757f89b566fc0372cd51b41351c3b6f237']
//Amount to stake
posList = [2]
//Gas price and gas limit are to compute the gas costs of the transaction.
const gasPrice = '2500'
const gasLimit = '20000'
//Payer's address to pay for the transaction gas
const tx = GovernanceTxBuilder.makeAuthorizeForPeerTx(address, peerPubKeyList, posList, address, gasPrice, gasLimit)

TransactionBuilder.signTransaction(tx, privateKey) // BUG with ed25519?

console.log('signed tx', tx)

// serialize tx ready to broadcast

const serialized = tx.serialize()
console.log('tx serialized', serialized)
```

I get this error when serializing the tx:

```
RangeError: num (57.5) must be a safe integer
    at Ee (/mnt/SSD-EVO/PROVE2/ontology-prove/node_modules/ontology-ts-sdk/lib/index.js:1:21252)
    at dt (/mnt/SSD-EVO/PROVE2/ontology-prove/node_modules/ontology-ts-sdk/lib/index.js:1:33749)
    at /mnt/SSD-EVO/PROVE2/ontology-prove/node_modules/ontology-ts-sdk/lib/index.js:1:34010
    at vt (/mnt/SSD-EVO/PROVE2/ontology-prove/node_modules/ontology-ts-sdk/lib/index.js:1:34031)
    at e.value (/mnt/SSD-EVO/PROVE2/ontology-prove/node_modules/ontology-ts-sdk/lib/index.js:1:71196)
```

It works fine without the EDDSA ED25519 crypto schema.

**Comment by roccomuso** [comment]
Looks like might be a bug in:

https://github.com/ontio/ontology-ts-sdk/blob/b73e80c71d6989ee14f41fd9e62e385b1b14ac28/src/crypto/PublicKey.ts#L103

That is not encoded. Replacing it with `Buffer.from(this.key, 'hex').toString('hex')` fixes it.

**Comment by MickWang** [comment]
https://github.com/ontio/ontology-ts-sdk/pull/198 
Already fixed it. Thanks a lot.
